### ISSUE TITLE
Add aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [geventhttpclient/geventhttpclient#138]
**Problem description:**
Installing geventhttpclient through pip on aarch64 downloads its source distribution from PyPi and builds it rather than directly downloading the wheels and installing it. Also, user requires development environment to be installed to build and install form the source distribution. 

**Expected resolution:**
Pip should be able to download and install aarch64 wheels from PyPi.

**Comment by cyberw** [comment]
I was not able to get it to work :(
