### ISSUE TITLE
ERROR: A new response began before end of HTTPSocketPoolResponse

### ISSUE THREAD

**Issue by JingYang0725** [geventhttpclient/geventhttpclient#144]
this question come from [https://github.com/locustio/locust/issues/1804](https://github.com/locustio/locust/issues/1804)

Descriptions:
I want to read the user's request data from the database and play it back

Such as:

User A has 1000 requests in the database, I will play back the 1000 requests

But I got an error

Error Detail:
ERROR: A new response began before end of <HTTPSocketPoolResponse status=200 headers={'date': 'Mon, 05 Jul 2021 03:48:06 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '42', 'connection': 'keep-alive'}>

Steps to reproduce
1. Prepare 1000 request data,  Contains a variety of different methods(GET/POST/PUT/OPTIONS), at least four (less than 1000 is acceptable)
2. do requests

**Comment by cyberw** [comment]
Sounds like an improper response from the HTTP server. Unless you have more details there’s not a lot I can say…

**Comment by ml31415** [comment]
Thanks for reporting this issue. It would be helpful, if you could provide a full reproducer, not just a rough description on what you attempted to do. This means, a minimal code snippet, doing all the necessary setup of the database, and the full code, including all setup, to reproduce the issue.
