### ISSUE TITLE
Writing unit tests for code that use geventhttpclient

### ISSUE THREAD

**Issue by sboisson** [geventhttpclient/geventhttpclient#148]
Existing HTTP client mocking libs like [httpretty](https://httpretty.readthedocs.io/) or [pook](https://pook.readthedocs.io/) do not really support gevent (only standard API monkey patched by gevent, not gevent API as used by geventhttpclient)… 
And running a temporary web server is not always easy or practical.

Is there any other third party HTTP mocking lib with support for ?

If not, a [mock engine for pook](https://pook.readthedocs.io/en/latest/api.html#pook.Engine) could be a great addition.

**Comment by ml31415** [comment]
Sounds like a cool library. About mocking, please have a look at the current test suite. It contains also a lot of mocking, to keep the runtime down, reduce external dependencies etc. You'll find a `wsgiserver` and a `server` context manager, which should basically do, what you're looking for.

https://github.com/geventhttpclient/geventhttpclient/blob/571f71da33852ced8a3bd62560dbbfb08ee066f1/src/geventhttpclient/tests/test_client.py#L27-L33

And being used like this:

https://github.com/geventhttpclient/geventhttpclient/blob/571f71da33852ced8a3bd62560dbbfb08ee066f1/src/geventhttpclient/tests/test_client.py#L353-L356
