### ISSUE TITLE
Http pipelining support

### ISSUE THREAD

**Issue by sriram-kondakindi** [geventhttpclient/geventhttpclient#164]
Does geventhttpclient support pipeling?

**Comment by ml31415** [comment]
Yes, that's one of the key features of this library. You can set the concurrency on `HTTPClient` or `UserAgent` objects using the `concurrency=` keyword argument.

**Comment by ml31415** [comment]
No, it doesn't, and probably won't be anytime soon. It only supports opening several connections in parallel. For this, you can set the concurrency on `HTTPClient` or `UserAgent` objects using the `concurrency=` keyword argument.
