### ISSUE TITLE
Difference between connection_timeout and network_timeout

### ISSUE THREAD

**Issue by jbkyang-nvi** [geventhttpclient/geventhttpclient#183]
Hello, I was trying to use the HttpClient and a little confused about the difference between `connection_timeout` and `network_timeout`. 
From my understanding `connection_timeout` is the timeout of when the client can get a connection to the server as seen from [this test](https://github.com/geventhttpclient/geventhttpclient/blob/c4a256f07fc8bc16e4716dfc29152caa5604285f/src/geventhttpclient/tests/test_ssl.py#L210-L243). But not sure how that is different from using
`network_timeout` from [this test](https://github.com/geventhttpclient/geventhttpclient/blob/c4a256f07fc8bc16e4716dfc29152caa5604285f/src/geventhttpclient/tests/test_ssl.py#L250-L261)

Would `network_timeout` timeout for that specified value on each `get()`? Or is it the total length of connection?

Is there a better place to read about this? Can I find documentation somewhere?

**Comment by ml31415** [comment]
See here, these parameters are just passed down to the socket.
https://stackoverflow.com/questions/3069382/what-is-the-difference-between-connection-and-read-timeout-for-sockets

**Comment by jbkyang-nvi** [comment]
@ml31415 here `read timeout` is the `network_timeout` param?

**Comment by ml31415** [comment]
I didn't recheck the code, but yes, guess so.
