### ISSUE TITLE
Saving cookies on non-success http responses

### ISSUE THREAD

**Issue by onestay** [geventhttpclient/geventhttpclient#187]
I need some cookies to be set in the cookie jar which have are included in a HTTP response with status code 401. I narrowed it down to the following:
https://github.com/geventhttpclient/geventhttpclient/blob/eb662c6c19517e9c65dc861eee5cb510976dec84/src/geventhttpclient/useragent.py#L468-L482

The cookies are only added to the jar after the status is checked, which in this case raises an exception due to the 401 status code.

The current behavior seems wrong, since both python requests as well as browsers (at least I tested it in Firefox) do save these cookies.

**Comment by cyberw** [comment]
Yes, that looks like a mistake. Can you make a PR? Ideally with a test case, but even without it is good.
