### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by ml31415** [geventhttpclient/geventhttpclient#190]
It's about time, isn't it? That would allow for some spring cleanup as well, using black, pyproject usw. @gwik @cyberw what's your thoughts?

**Comment by cyberw** [comment]
I'm all for it, if you are willing to do it :) 

I have a slight preference for using ruff as a formatter, if that is ok with you (the result of the formatting is the same it just needs the settings in a different place in pyproject - see for example https://github.com/locustio/locust/blob/master/pyproject.toml#L63)

**Comment by ml31415** [comment]
Yeah, ruff is great, agreed. What about python 3.6-3.8? Could be dropped as well imho. So we could start using type hints.

**Comment by cyberw** [comment]
Definitely ok to drop 3.6 and 3.7.... yea, lets drop 3.8 too. 

3.8 end of life this fall anyway, and there's nothing stopping people from staying on an old release if they are on 3.8...

**Comment by ml31415** [comment]
Ok, then let's do it. I'll draft smth later today.

**Comment by cyberw** [comment]
Ideally _someone_ would have a look at updating llhttp to latest as well :)

Our version is a couple years old...
