### ISSUE TITLE
Drop windows support

### ISSUE THREAD

**Issue by ml31415** [geventhttpclient/geventhttpclient#194]
The test cases for windows were deactivated quite a while ago, as they're either hanging or crashing. Right now due to the disabled tests, it looks like windows would be fully supported, even if it isn't. We're just building broken packages. Either we should get these issues fixed or be honest and drop it from the list of supported systems. @gwik @cyberw thoughts?

**Comment by cyberw** [comment]
IIRC, it worked fine when I tried using it on windows (using Locust, but not mostly doing basic stuff), so I didnt want to stop building for windows. I might not have time to test it right now, but I would much prefer fixing the issues :)
