### ISSUE TITLE
Testpypi missing for packaging test runs

### ISSUE THREAD

**Issue by ml31415** [geventhttpclient/geventhttpclient#202]
We should replicate the package build action using https://test.pypi.org/ so that we can safely test the publishing without sending unintended packages to the world. See e.g. https://github.com/ml31415/numpy-groupies/blob/master/.github/workflows/pypi-release.yaml for a sample setup. Issues as recently happened with #201 would be avoidable.

**Comment by ml31415** [comment]
@cyberw as you have all the keys for pypi already, would you mind registering at https://test.pypi.org as well and provide the necessary tokens to github.com?

**Comment by cyberw** [comment]
I think I can do that. Not today though..

**Comment by cyberw** [comment]
I've registered and added a key for test pypi, using env var TEST_PYPI_API_TOKEN instead of PYPI_API_TOKEN.

If you let me know your pypi username I'll be happy to give you maintainer access, for future use :)

**Comment by ml31415** [comment]
Cool, thx! Username, same as here in github, for pypi and testpypi.

**Comment by cyberw** [comment]
Done!

**Comment by webknjaz** [comment]
@cyberw

> I've registered and added a key for test pypi, using env var TEST_PYPI_API_TOKEN instead of PYPI_API_TOKEN.

*(a drive by comment)* consider using tokenless uploads — it's easier to maintain and is not bound to user accounts: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
