### ISSUE TITLE
No Windows wheels present anymore

### ISSUE THREAD

**Issue by mrijken** [geventhttpclient/geventhttpclient#205]
Since version 2.1.0/2.1.1 there are no wheel for Windows present anymore (https://pypi.org/project/geventhttpclient/2.1.1/#files).  Is that by accident or purpose?

**Comment by ml31415** [comment]
Accident. Though the test cases have quite some issues with windows.

**Comment by ml31415** [comment]
@cyberw Looks like the windows wheels were built correctly ( https://github.com/geventhttpclient/geventhttpclient/actions/runs/8642671493/artifacts/1404111352 ) , just not uploaded as supposed. Looks like someone with pypi access needs to dig into this.

**Comment by cyberw** [comment]
Does it work now? (2.2.0)

**Comment by mrijken** [comment]
Yes, it works. Thanx
