### ISSUE TITLE
breaking changes in 2.3.0

### ISSUE THREAD

**Issue by cyberw** [geventhttpclient/geventhttpclient#217]
It seems 2.3.0 accidentally introduced some breaking changes. I have pinned locust to use 2.2.1 for now (no time to look deeper into it at the moment)

https://github.com/locustio/locust/actions/runs/8743911866/job/23995599616

**Comment by ml31415** [comment]
Yeah, when refactoring UserAgent, I had moved _make_request into a plain function. Not a big deal, to bring it back.

**Comment by cyberw** [comment]
(feel free to close this as invalid if you think it is)

**Comment by cyberw** [comment]
Or maybe, if it is easy then bring it back for now. If someone installs locust < 2.26 (before the pin) they will get geventhttpclient 2.3.0, which will cause some issues...

**Comment by ml31415** [comment]
Well, I had a short look at LocustUserAgent while working on the refactoring, but unfortunately I missed that dependency on internals. We can change it on geventhttpclient, but in the end I guess we should aim for a solution, that works for Locust without depending on internals and create the necessary hooks to overwrite as non-private functions. Or take the functionality over to geventhttpclient, if it fits the scope. I'd need to have a closer look what you do.

In any case, we could have a 2.3.1, that has a `_make_request`calling the new function, while remaining backwards compatible.

**Comment by cyberw** [comment]
Yes, I have a ticket on myself to do something like that https://github.com/locustio/locust/issues/2681

**Comment by ml31415** [comment]
2 minutes for another pull shark ... :)

**Comment by ml31415** [comment]
@cyberw you do the 2.3.1?

**Comment by cyberw** [comment]
Ok!
