### ISSUE TITLE
Add Proxy Error

### ISSUE THREAD

**Issue by GeraldWhitehead** [geventhttpclient/geventhttpclient#222]
When requesting an interface, adding a proxy gives an error, but using the requests library makes the request successful.
![image](https://github.com/geventhttpclient/geventhttpclient/assets/167045125/5930353f-b40a-4277-8a97-0a808975d20e)
Looking at the source code, the following error is reported here, but the urlopen function is not passing the proxy through
![image](https://github.com/geventhttpclient/geventhttpclient/assets/167045125/d153c914-0d7b-41cb-90c9-1e33798e15bf)
Can you tell me how to use the agent correctly?
The version I'm using is 2.3.1

**Comment by ml31415** [comment]
Proxies are currently not supported, see:
https://github.com/geventhttpclient/geventhttpclient/issues/184
