### ISSUE TITLE
Breaking changes introduced in 2.0.4

### ISSUE THREAD

**Issue by yinggeh** [geventhttpclient/geventhttpclient#225]
Recently Triton Inference Server is moving to Python 3.12 environment so we had to update geventhttpclient version>= 2.0.11. This PR https://github.com/geventhttpclient/geventhttpclient/pull/170 was introduced since [2.0.4](https://github.com/geventhttpclient/geventhttpclient/releases/tag/2.0.4) broke our tests. I tried with 2.3.1 and the issue persisted.

```
def _connect_socket(self, sock, address):
    sock = super()._connect_socket(sock, address)

    if self.ssl_context is None:
        return gevent.ssl.wrap_socket(sock, **self.ssl_options)
    else:
        server_hostname = self.ssl_options.get("server_hostname", self._request_host)
        return self.ssl_context.wrap_socket(sock, server_hostname=server_hostname)
```
The problem I can see here is that we pass `ssl_context_factory==None` and `ssl_options` with custom values like "keyfile" and "certfile" in [ \_\_init\_\_](https://github.com/geventhttpclient/geventhttpclient/blob/2.3.1/geventhttpclient/connectionpool.py#L230). However, after this PR `self.ssl_context` is never None `ssl_options` custom values are never used. See [example](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_http_infer_client.py#L180-L198) from Triton Python client.

**Comment by ml31415** [comment]
Thanks for the bug report. Yeah, completely ignoring the `ssl_options` is clearly not the idea.

**Comment by yinggeh** [comment]
Hi @ml31415. Thanks for the quick response. Do you have an estimated time for fixing the bug as well as the release time?

**Comment by ml31415** [comment]
Please have a look if this is fixed for you.

**Comment by yinggeh** [comment]
@ml31415 Thanks for the quick fix. I will run a test to verify. Meanwhile, shouldn't the tag be 2.3.2 instead of 2.3.3?

**Comment by ml31415** [comment]
Yes and no. The deploy to test-pypi worked, but the main deploy was skipped for whatever reason by the github action, so I had to increase twice.

**Comment by yinggeh** [comment]
I can confirm https://github.com/geventhttpclient/geventhttpclient/commit/acab216a7131fff2fb897e65041ea285290e4a5d has fixed the issue. Can you please confirm `pip install geventhttpclient==2.3.2` is stable?

**Comment by ml31415** [comment]
2.3.3 will do the trick. 2.3.2 only exists on test.pypi.org

**Comment by ml31415** [comment]
@yinggeh I finally fixed the versioning issues and triggered new release, so please go with 2.3.3 as soon as the build and publishing finishes.

**Comment by yinggeh** [comment]
Thanks! @ml31415
